### ISSUE TITLE
Switch to using jetty-home distribution instead of jetty-distribution

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/jetty-runtime#102]

**Comment by gregw** [comment]
I've created a branch for this at https://github.com/GoogleCloudPlatform/jetty-runtime/tree/master-102, but since it is branched off https://github.com/GoogleCloudPlatform/jetty-runtime/tree/master-85, I've not yet created a PR.

Initial local testing is good, but I'm currently behind a very limited network, so I've not yet done any real deployments with it.

**Comment by gregw** [comment]
If we want to get rid of the -version extension on the jetty-home directory, we can probably use the `unpack` goal instead of the `copy` goal of the `maven-dependency-plugin` and then ADD as a directory rather than as an archive.

However, I rather like the -version extension for documentation and most uses should use $JETTY_HOME or ${jetty.home} and need not be bothered by it.

**Comment by meltsufin** [comment]
What do you mean by the `-version extension` and how is it affected by the move to the jetty-home distribution?

**Comment by gregw** [comment]
I was just picking up on your discussion in the other thread about how to unpack the war to a directory called `jetty-home` rather than `jetty-home-9.4.x.v2016xxxx'.   You asked about maven magic to do that and we can probably achieve that simply as described above.   However, I have a slight preference for keeping the version in the directory name, but it is only slight.

**Comment by meltsufin** [comment]
Oh, I see what you meant now. The issue I see with the version as part of the directory name is that it changes the default CMD with every new release of Jetty, and some users may want provide a custom CMD in their Dockerfile and not have to change it every time we update the image. So, I'm curious to see how unpack could be used to achieve this.

**Comment by gregw** [comment]
OK I'll try my mvn-foo out to see if it can be done simply.  Stand-by...
