### ISSUE TITLE
How can you run a Java Profiler?

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/jetty-runtime#59]
@janbartel @gregw @joakime @jmcc0nn3ll 
A customer has asked this question. Do you guys have any recommendations for this?

**Comment by jmcc0nn3ll** [comment]
@meltsufin We have the most experience using yourkit but we also use jprofiler from time to time.  They are generally fine for testing scenarios but we shy away from using them in production.  Typically the easiest way to set them up is to drop their agent library into the jetty.home/lib directory and add the agent on the command line for startup.  This does raise a point that we ought to consider making an mod file to make enabling these easier, probably not something we can include in the general distribution but something that could perhaps be added into this image and enabled through an environment variable or custom docker file.

@gregw Think we should add in a .mod file for yourkit?  How would we recommend a client to access the container?  

@meltsufin If you are exposing jmx information at all to things like jmc on a user desktop then this would be another setup like that, otherwise typically the profilers will open up a port that users can connect the profilers UI to and then interact with that.  I am assuming that is what your client is interested in here, do you know what the process for that is?  If memory serves there was some configuration in the dockerfile involved on what ports to export...

@sbordet Do you have any suggestions on running a profiler in a setup like this?

**Comment by sbordet** [comment]
If the question is how to run a profiler in a development environment, most if not all of them come with IDE integration, so it's typically very easy and well documented by each vendor.

If the profiler needs to be run in production, I would recommend only JMC (Java Mission Control) and Flight Recorder. The reason is that most if not all other profilers use JVMTI in a way that disables JIT optimizations, see http://psy-lob-saw.blogspot.it/2014/12/the-escape-of-arraylistiterator.html.
Therefore the only low-impact profiler is for now only JMC.

Unfortunately (last time I checked), to run Flight Recorder in production you need to contact Oracle and pay (and from what I heard, it is **not** cheap). You may get by with just JMC, however, depending on what details you want to see, and that does not need Oracle be involved.

Automating the start of the profiler with the start of Jetty may be some work though, as profilers typically need either a Java agent (simpler) or to know the PID of the process to profile (harder).

**Comment by meltsufin** [comment]
The question has been resolved for the customer. Closing...
