### ISSUE TITLE
/app not owned by jetty user

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/jetty-runtime#85]
https://github.com/GoogleCloudPlatform/jetty-runtime/blob/master/jetty9/src/main/docker/Dockerfile#L41
It looks like with need to `chown -R jetty:jetty /app`, or am I missing something? @gregw @jmcc0nn3ll

**Comment by janbartel** [comment]
@meltsufin in some ways its good to keep the app read-only: means that it can't mutate. Jetty itself won't modify anything in /app, we only need read permission. I guess we could chown /app, but is there a specific use-case you want to address by doing that?

**Comment by meltsufin** [comment]
@janbartel I agree with your point about `/app` only needing to be readable by `jetty`.
The real problem I'm facing is deploying an exploded WAR.
The Dockerfile looks like this:
```
FROM jetty:9.3
ADD root /app
```
Where `root` contains the exploded WAR.

When I try to run the container, I get this:
```
2016-12-06 16:48:16.955:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@20e2cbe0{/,file:///var/lib/jetty/webapps/root/,null}{/root}
java.nio.file.AccessDeniedException: /var/lib/jetty/webapps/root/WEB-INF/web.xml
```

Is this something where we expect the user to add `RUN chmod -R +r /app` to the Dockerfile?

I tried this, and it sort of works, but then `/` route shows a directory listing `WEB-INF` and `META-INF`.

**Comment by jmcc0nn3ll** [comment]
The way I am reading the current setup is that under the jetty installation we link the webapps/root directory to the /app directory which means the unexploded war should dumped into this directory.

For deploying to the root context typically we see folks drop a root.war file in the webapps directory, or they drop a custom context.xml that maps a specific war file to the context which is then exploded by the jetty deployer....or they put the exploded war file themselves in the webapps/root directory (which is currently symbolically linked to the /app directory in the container.

Likely I am missing something here but I see the local and remote tests from #72 working with this exploded setup and it is not clear to me how deploying a war file is supposed to work in this setup?  Someone needs to explode it and I don't see how Jetty is intended to do that unless it is dropped in the /var/lib/jetty/webapps directory and renamed root.war.

**Comment by meltsufin** [comment]
@jmcc0nn3ll You're right, adding the war to `/app` is not going to work. What we typically do is something like this `ADD myapp.war $JETTY_BASE/webapps/root.war`. I'm not sure why exactly `/app` link was introduced and where it's used/documented.

**Comment by gregw** [comment]
My understanding is that the /app link is/was used by the previous gcloud maven plugin (gcloud:deploy).  We inherited it from compat.

If it is not required by flex, then let's get rid of it as sym links are just asking for trouble (yes they do work in Jetty, but they make all the security checks more difficult as every file is an alias)!

When you get the exception, it is on an exploded war file.  Was that expanded by: a) the maven plugin; b) custom dockerfile; c) jetty ?

If it was expanded by jetty, it should be be owned by jetty.

I think long term having the war exploded by the plugin is a much better idea because if the war is put into the image then either CPU is wasted on every startup unpacking it and memory is always wasted as the running image contains both packed and unpacked war.    Note that even if you unpack in a custom docker file, the war file will remain in the docker image, wasting space on disk and making image transfers longer etc.

See:
- https://github.com/GoogleCloudPlatform/jetty-runtime/issues/11
- https://github.com/docker/docker/issues/6119

**Comment by meltsufin** [comment]
I looked more into it, and yes, `/app` is used by the old gcloud-maven-plugin, as well as the Cloud SDK when it auto-generates the Dockerfile for openjdk-runtime and jetty compat.  So, we can't get rid of the symlink immediately, but maybe later.

I think we want to support deployment of either WAR or exploded WAR. The tools should pick the exploded WAR from the efficiently point of view.

I think the reason we expand the WAR in the `docker-entrypoint.bash` rather than allow Jetty to do it is because the Stackdriver Debugger needs to load the classes before Jetty starts up. See the comment in the Dockerfile:
```
# Unpack a WAR app (if present) beforehand so that Stackdriver Debugger
# can load it. This should be done before the JVM for Jetty starts up.
```
Regarding running as the jetty user, I can't find where we're switching user to jetty.

**Comment by jmcc0nn3ll** [comment]
user to Jetty is in the Dockerfile I believe

--
jesse mcconnell
jesse.mcconnell@gmail.com

**Comment by meltsufin** [comment]
I think I figured it out. The Jetty setuid module is added in the Dockerfile, which by default starts Jetty under the jetty user.
```
RUN java -jar $JETTY_HOME/start.jar --add-to-startd=setuid \
...
```
Then in `/usr/local/jetty/modules/setuid.mod`:
```
...
[ini-template]
## SetUID Configuration
# jetty.setuid.startServerAsPrivileged=false
# jetty.setuid.userName=jetty
# jetty.setuid.groupName=jetty
# jetty.setuid.umask=002
...
```

**Comment by jmcc0nn3ll** [comment]
yes, and those commented out parameters are the default settings

**Comment by gregw** [comment]
Oh I had assumed we were using a `USER` command in the dockerfile rather than setuid.

This means that the docker-entrypoint.bash command is running as root and thus it should do a chown after it unpacks any war file.

Alternately we could add a USER command to the dockerfile and remove the setuid module.   setuid is only really needed if we want to listen on port 80 or do some other privileged operations before starting the webapp context.    Avoiding setuid does avoid the issue of creating other root owned files.

So I think for this issue we should:
- remove the symlink that is created in the `Dockerfile`
- update `docker-entrypoint.bash` to look for content in app and only create the symlink if needed
- remove the setuid module
- add `USER jetty` to the `Dockerfile`

I'll prepare a PR along those lines
